### PR TITLE
Merge NERR metrics back into master.

### LINKED ISSUE #11: Merge ERR Inspired Metrics into one class
@JMMackenzie to merge the ERR inspired into one class
 Speak to @ammoffat regarding the name of the ERR Inspired classes. Proposed name is err_e8, err_e9, etc. given the c functions in the paper.

### PR DESCRIPTION
**Pull request by JMMackenzie**
Creating this as a draft PR until we fix the remaining issues.

Currently fixes #11 and #12 and partially addresses #13.

### CODE REVIEW

**Comment by JMMackenzie** [comment]
Updated to now address #14 as well.

@leifos I think you can take a look now and address #13 (update the README and descriptions).

Then I think we're good to go for the merge and new release :-)

**Comment by JMMackenzie** [comment]
Also now checks:

(1) the `max_gain` provided by the command line is not exceeded in the gains file, and
(2) that the gains are all in the range [0, 1] (only currently implemented for INST and the NERR metrics).

**Comment by JMMackenzie** [comment]
@leifos this is probably ready to be reviewed and merged, but we might want to decide how to approach #17 first?

**Review by leifos — COMMENTED** [review]
- change args.max_gain to args.residual_max_gain to make it clearer that this property is for the residual computation
- update the validate_gain_range function to use np.min and np.max functions (on the belief it will be faster :-) )

**Pull request merged**
